import type { Metadata } from "next";

import "./styles/globals.css";
import Header from "./src/components/layouts/Header";
import Footer from "./src/components/layouts/Footer";





export const metadata: Metadata = {
  title: "Survey App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
